export default {
  START_INSETS_FETCHING: "START_INSETS_FETCHING",
  SET_INSETS: "SET_INSETS",
  SET_INSET: "SET_INSET",
  ADD_INSET: "ADD_INSET",
  UPDATE_INSET: "UPDATE_INSET",
  DELETE_INSET: "DELETE_INSET"
}